// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db_entities

import (
	"time"
)

type CalendarEvent struct {
	ID       int64
	Title    string
	DateTime time.Time
	OwnerID  int64
}

type Participation struct {
	UserID  int64
	EventID int64
}

type Session struct {
	ID     string
	UserID int64
}

type User struct {
	ID       int64
	UserName string
	Password string
}
