// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file auth.proto (edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth.proto.
 */
export const file_auth: GenFile = /*@__PURE__*/
  fileDesc("CgphdXRoLnByb3RvIi0KC0xvZ2luUGFyYW1zEgwKBG5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAlCC1oJcHJvdG8ucGtnYghlZGl0aW9uc3DoBw");

/**
 * @generated from message LoginParams
 */
export type LoginParams = Message<"LoginParams"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message LoginParams.
 * Use `create(LoginParamsSchema)` to create a new message.
 */
export const LoginParamsSchema: GenMessage<LoginParams> = /*@__PURE__*/
  messageDesc(file_auth, 0);

