// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file event.proto (edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file event.proto.
 */
export const file_event: GenFile = /*@__PURE__*/
  fileDesc("CgtldmVudC5wcm90byI9ChtMaXN0RXZlbnRzV2l0aE93bmVyUmVzcG9uc2USHgoGZXZlbnRzGAEgAygLMg4uRXZlbnRBbmRPd25lciI9Cg1FdmVudEFuZE93bmVyEhUKBWV2ZW50GAEgASgLMgYuRXZlbnQSFQoFb3duZXIYAiABKAsyBi5Pd25lciJRCgVFdmVudBIKCgJpZBgBIAEoAxINCgV0aXRsZRgCIAEoCRItCglkYXRlX3RpbWUYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIiEKBU93bmVyEgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkiaQoRQ3JlYXRlRXZlbnRQYXJhbXMSDQoFdGl0bGUYASABKAkSLQoJZGF0ZV90aW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIWCg5pbnZpdGVkVXNlcklkcxgDIAMoAyIfChFEZWxldGVFdmVudFBhcmFtcxIKCgJpZBgBIAEoAyJLChNDcmVhdGVFdmVudFJlc3BvbnNlEgwKAmlkGAEgASgDSAASFwoNZXJyb3JfbWVzc2FnZRgCIAEoCUgAQg0KC2lkX29yX2Vycm9yQgtaCXByb3RvLnBrZ2IIZWRpdGlvbnNw6Ac", [file_google_protobuf_timestamp]);

/**
 * @generated from message ListEventsWithOwnerResponse
 */
export type ListEventsWithOwnerResponse = Message<"ListEventsWithOwnerResponse"> & {
  /**
   * @generated from field: repeated EventAndOwner events = 1;
   */
  events: EventAndOwner[];
};

/**
 * Describes the message ListEventsWithOwnerResponse.
 * Use `create(ListEventsWithOwnerResponseSchema)` to create a new message.
 */
export const ListEventsWithOwnerResponseSchema: GenMessage<ListEventsWithOwnerResponse> = /*@__PURE__*/
  messageDesc(file_event, 0);

/**
 * @generated from message EventAndOwner
 */
export type EventAndOwner = Message<"EventAndOwner"> & {
  /**
   * @generated from field: Event event = 1;
   */
  event?: Event;

  /**
   * @generated from field: Owner owner = 2;
   */
  owner?: Owner;
};

/**
 * Describes the message EventAndOwner.
 * Use `create(EventAndOwnerSchema)` to create a new message.
 */
export const EventAndOwnerSchema: GenMessage<EventAndOwner> = /*@__PURE__*/
  messageDesc(file_event, 1);

/**
 * @generated from message Event
 */
export type Event = Message<"Event"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: google.protobuf.Timestamp date_time = 3;
   */
  dateTime?: Timestamp;
};

/**
 * Describes the message Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_event, 2);

/**
 * @generated from message Owner
 */
export type Owner = Message<"Owner"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message Owner.
 * Use `create(OwnerSchema)` to create a new message.
 */
export const OwnerSchema: GenMessage<Owner> = /*@__PURE__*/
  messageDesc(file_event, 3);

/**
 * @generated from message CreateEventParams
 */
export type CreateEventParams = Message<"CreateEventParams"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: google.protobuf.Timestamp date_time = 2;
   */
  dateTime?: Timestamp;

  /**
   * @generated from field: repeated int64 invitedUserIds = 3;
   */
  invitedUserIds: bigint[];
};

/**
 * Describes the message CreateEventParams.
 * Use `create(CreateEventParamsSchema)` to create a new message.
 */
export const CreateEventParamsSchema: GenMessage<CreateEventParams> = /*@__PURE__*/
  messageDesc(file_event, 4);

/**
 * @generated from message DeleteEventParams
 */
export type DeleteEventParams = Message<"DeleteEventParams"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message DeleteEventParams.
 * Use `create(DeleteEventParamsSchema)` to create a new message.
 */
export const DeleteEventParamsSchema: GenMessage<DeleteEventParams> = /*@__PURE__*/
  messageDesc(file_event, 5);

/**
 * @generated from message CreateEventResponse
 */
export type CreateEventResponse = Message<"CreateEventResponse"> & {
  /**
   * @generated from oneof CreateEventResponse.id_or_error
   */
  idOrError: {
    /**
     * @generated from field: int64 id = 1;
     */
    value: bigint;
    case: "id";
  } | {
    /**
     * @generated from field: string error_message = 2;
     */
    value: string;
    case: "errorMessage";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message CreateEventResponse.
 * Use `create(CreateEventResponseSchema)` to create a new message.
 */
export const CreateEventResponseSchema: GenMessage<CreateEventResponse> = /*@__PURE__*/
  messageDesc(file_event, 6);

