// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file generic.proto (edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file generic.proto.
 */
export const file_generic: GenFile = /*@__PURE__*/
  fileDesc("Cg1nZW5lcmljLnByb3RvIiAKDUVycm9yUmVzcG9uc2USDwoHbWVzc2FnZRgBIAEoCUILWglwcm90by5wa2diCGVkaXRpb25zcOgH");

/**
 * @generated from message ErrorResponse
 */
export type ErrorResponse = Message<"ErrorResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message ErrorResponse.
 * Use `create(ErrorResponseSchema)` to create a new message.
 */
export const ErrorResponseSchema: GenMessage<ErrorResponse> = /*@__PURE__*/
  messageDesc(file_generic, 0);

