// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file user.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user.proto.
 */
export const file_user: GenFile = /*@__PURE__*/
  fileDesc("Cgp1c2VyLnByb3RvIjIKEENyZWF0ZVVzZXJQYXJhbXMSDAoEbmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSItChFTaGFyZWFibGVVc2VyRGF0YRIKCgJpZBgBIAEoBRIMCgRuYW1lGAIgASgJIi0KCFVzZXJMaXN0EiEKBXVzZXJzGAEgAygLMhIuU2hhcmVhYmxlVXNlckRhdGFCC1oJcHJvdG8ucGtnYgZwcm90bzM");

/**
 * @generated from message CreateUserParams
 */
export type CreateUserParams = Message<"CreateUserParams"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message CreateUserParams.
 * Use `create(CreateUserParamsSchema)` to create a new message.
 */
export const CreateUserParamsSchema: GenMessage<CreateUserParams> = /*@__PURE__*/
  messageDesc(file_user, 0);

/**
 * paswordless user
 *
 * @generated from message ShareableUserData
 */
export type ShareableUserData = Message<"ShareableUserData"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message ShareableUserData.
 * Use `create(ShareableUserDataSchema)` to create a new message.
 */
export const ShareableUserDataSchema: GenMessage<ShareableUserData> = /*@__PURE__*/
  messageDesc(file_user, 1);

/**
 * @generated from message UserList
 */
export type UserList = Message<"UserList"> & {
  /**
   * @generated from field: repeated ShareableUserData users = 1;
   */
  users: ShareableUserData[];
};

/**
 * Describes the message UserList.
 * Use `create(UserListSchema)` to create a new message.
 */
export const UserListSchema: GenMessage<UserList> = /*@__PURE__*/
  messageDesc(file_user, 2);

