// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: event.proto

package proto_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListEventsWithOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventAndOwner       `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsWithOwnerResponse) Reset() {
	*x = ListEventsWithOwnerResponse{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsWithOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsWithOwnerResponse) ProtoMessage() {}

func (x *ListEventsWithOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsWithOwnerResponse.ProtoReflect.Descriptor instead.
func (*ListEventsWithOwnerResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *ListEventsWithOwnerResponse) GetEvents() []*EventAndOwner {
	if x != nil {
		return x.Events
	}
	return nil
}

type EventAndOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	Owner         *Owner                 `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAndOwner) Reset() {
	*x = EventAndOwner{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAndOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAndOwner) ProtoMessage() {}

func (x *EventAndOwner) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAndOwner.ProtoReflect.Descriptor instead.
func (*EventAndOwner) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventAndOwner) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventAndOwner) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_time,json=dateTime" json:"date_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Event) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Event) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

type Owner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *Owner) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Owner) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type CreateEventParams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          *string                `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	DateTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_time,json=dateTime" json:"date_time,omitempty"`
	InvitedUserIds []int64                `protobuf:"varint,3,rep,packed,name=invitedUserIds" json:"invitedUserIds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateEventParams) Reset() {
	*x = CreateEventParams{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventParams) ProtoMessage() {}

func (x *CreateEventParams) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventParams.ProtoReflect.Descriptor instead.
func (*CreateEventParams) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *CreateEventParams) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *CreateEventParams) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *CreateEventParams) GetInvitedUserIds() []int64 {
	if x != nil {
		return x.InvitedUserIds
	}
	return nil
}

type DeleteEventParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventParams) Reset() {
	*x = DeleteEventParams{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventParams) ProtoMessage() {}

func (x *DeleteEventParams) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventParams.ProtoReflect.Descriptor instead.
func (*DeleteEventParams) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEventParams) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type CreateEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to IdOrError:
	//
	//	*CreateEventResponse_Id
	//	*CreateEventResponse_ErrorMessage
	IdOrError     isCreateEventResponse_IdOrError `protobuf_oneof:"id_or_error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *CreateEventResponse) GetIdOrError() isCreateEventResponse_IdOrError {
	if x != nil {
		return x.IdOrError
	}
	return nil
}

func (x *CreateEventResponse) GetId() int64 {
	if x != nil {
		if x, ok := x.IdOrError.(*CreateEventResponse_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *CreateEventResponse) GetErrorMessage() string {
	if x != nil {
		if x, ok := x.IdOrError.(*CreateEventResponse_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return ""
}

type isCreateEventResponse_IdOrError interface {
	isCreateEventResponse_IdOrError()
}

type CreateEventResponse_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,oneof"`
}

type CreateEventResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,oneof"`
}

func (*CreateEventResponse_Id) isCreateEventResponse_IdOrError() {}

func (*CreateEventResponse_ErrorMessage) isCreateEventResponse_IdOrError() {}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x1bListEventsWithOwnerResponse\x12&\n" +
	"\x06events\x18\x01 \x03(\v2\x0e.EventAndOwnerR\x06events\"K\n" +
	"\rEventAndOwner\x12\x1c\n" +
	"\x05event\x18\x01 \x01(\v2\x06.EventR\x05event\x12\x1c\n" +
	"\x05owner\x18\x02 \x01(\v2\x06.OwnerR\x05owner\"f\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x127\n" +
	"\tdate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\"+\n" +
	"\x05Owner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8a\x01\n" +
	"\x11CreateEventParams\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x127\n" +
	"\tdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12&\n" +
	"\x0einvitedUserIds\x18\x03 \x03(\x03R\x0einvitedUserIds\"#\n" +
	"\x11DeleteEventParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"]\n" +
	"\x13CreateEventResponse\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x12%\n" +
	"\rerror_message\x18\x02 \x01(\tH\x00R\ferrorMessageB\r\n" +
	"\vid_or_errorB\vZ\tproto.pkgb\beditionsp\xe8\a"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_event_proto_goTypes = []any{
	(*ListEventsWithOwnerResponse)(nil), // 0: ListEventsWithOwnerResponse
	(*EventAndOwner)(nil),               // 1: EventAndOwner
	(*Event)(nil),                       // 2: Event
	(*Owner)(nil),                       // 3: Owner
	(*CreateEventParams)(nil),           // 4: CreateEventParams
	(*DeleteEventParams)(nil),           // 5: DeleteEventParams
	(*CreateEventResponse)(nil),         // 6: CreateEventResponse
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
}
var file_event_proto_depIdxs = []int32{
	1, // 0: ListEventsWithOwnerResponse.events:type_name -> EventAndOwner
	2, // 1: EventAndOwner.event:type_name -> Event
	3, // 2: EventAndOwner.owner:type_name -> Owner
	7, // 3: Event.date_time:type_name -> google.protobuf.Timestamp
	7, // 4: CreateEventParams.date_time:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_event_proto_msgTypes[6].OneofWrappers = []any{
		(*CreateEventResponse_Id)(nil),
		(*CreateEventResponse_ErrorMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
